# Generated by Django 6.0.4 on 2026-04-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(max_length=120)),
                ('best_move', models.CharField(blank=True, max_length=20)),
                ('evaluation', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(default='fallback', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
